### ISSUE TITLE
Using oauth-browser-client with Nuxt

### ISSUE THREAD

**Issue by anbraten** [mary-ext/atcute#11]
Atcute is really well-designed and clean. Setting up OAuth and making the first API calls was straightforward.

However, I'm having an issue with Nuxt due to the global use of `navigator` in [runtime.ts](https://github.com/mary-ext/atcute/blob/3fcf7f990d494049f87d07e940fcc6550b7fbc67/packages/oauth/browser-client/lib/utils/runtime.ts#L3) Even though I only call the functions on the client side, Nuxt tries to import the code during server-side rendering, which causes an error. 

A possible solution might be wrapping the locks in a function that runs only when needed. Let me know if that’s something I could contribute. 

That said, since the package is called oauth-**browser**-client, it's understandable that it doesn’t work server-side. I also tried using `await import()`, but it would require making every related part async, which isn’t practical.

**Comment by mary-ext** [comment]
Yeah, that's fine, I'll add a check for navigator.
