### ISSUE TITLE
Contribution guide/setup

### ISSUE THREAD

**Issue by 43081j** [mary-ext/atcute#15]
Could you let us know what your workflow is when developing in this repo?

Maybe we can then document that in the README or a CONTRIBUTING doc

Locally, I've tried the following steps to build and test the client:

- `corepack enable && pnpm i`
- **fails** on node 23.x for me because of better-sqlite3's `make` failing with `"C++20 or later required"`
- so I then thought let's try an older node, 20 will do. **install now succeeds**
- next, there's no root `build` script afaict, so I figure out the dependencies and individually build each one so `client` can ultimately build
- at this point, I try `pnpm test` in the client dir. **this fails** because better-sqlite3 wants `NODE_MODULE_VERSION 131` and I have a lower one
- it turns out `131` appears to be 23.x, which I can't use since the install build/make fails (as seen above, chicken and egg situation)

so I think we just need to know what workflow you've been using to not run into any of this

node version, package manager, how you run builds, etc etc

i'd be happy to write the doc up once I understand, and maybe a root `build` and `test` script

edit:

with node 20.x I managed to get it all working 🙌

**Comment by mary-ext** [comment]
would this added contribution guide section help?
https://github.com/mary-ext/atcute/commit/d1615271af9d68cfc59103b4e17eb35e07e178d7

**Comment by 43081j** [comment]
Awesome, that looks good to me

It may also be worth mentioning you can run tests for one package using `pnpm run --filter="@atproto/client"`

Everything does seem to work using node 20 in the end

My setup was using corepack:

```sh
nvm use 20
corepack enable
pnpm i
```

**Comment by mary-ext** [comment]
sweet, I'll tack in a mention for pnpm as the package manager of choice, and a way to run tests for a specific package (normally when I work on a specific package, I'd just have a shell with that package's folder open)

**Comment by 43081j** [comment]
same here re having a shell open in the sub-package's directory

i think as long as we mention one of them (cd into the dir, or use `filter`), it makes it clear what the workflow is

thanks for looking at this so quickly too

**Comment by 43081j** [comment]
Closing since we now have a guide in the readme 👍
